#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with Minio console
## Usage: minio
## Example: "ddev minio"

echo "Login using 'ddevminio' user and 'ddevminio' password"

ddev launch http://127.0.0.1:9090
