name: denkit-stash
type: generic
docroot: .
webserver_type: generic
xdebug_enabled: false
additional_hostnames:
  - "denkit-stash"
  - "api.denkit-stash"
additional_fqdns: []
database:
    type: postgres
    version: "18"
use_dns_when_possible: true
web_environment:
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    - POSTGRES_DB=db
    - POSTGRES_USER=db
    - POSTGRES_PASSWORD=db
    - S3_ENDPOINT=rustfs:9000
    - S3_PUBLIC_ENDPOINT=http://rustfs:9000
    - S3_ACCESS_KEY=ddevrustfs
    - S3_SECRET_KEY=ddevrustfs
    - S3_BUCKET=denkit-storage
    - S3_USE_SSL=false
    - DENKIT_API_KEY_HASH_SECRET=denkit-ddev-api-key-hash-secret
corepack_enable: false
# Custom web build with latest Go and tools
webimage_extra_packages: []
web_extra_exposed_ports:
  - name: denkit-stash-api
    container_port: 8080
    http_port: 80
    https_port: 443
web_extra_daemons:
  - name: denkit-stash
    command: "/var/www/html/denkit-stash"
    directory: /var/www/html
hooks:
  pre-start:
    - exec-host: "go build -v -o denkit-stash ."
